import './bootstrap';

import Alpine from 'alpinejs';
import {
    createIcons,
    AlertCircle,
    AlertTriangle,
    AlignLeft,
    Archive,
    ArrowDownLeft,
    ArrowLeft,
    ArrowRight,
    BarChart3,
    Building,
    Building2,
    Briefcase,
    Check,
    CheckCircle2,
    ChevronDown,
    ChevronRight,
    ClipboardList,
    Clock,
    CreditCard,
    Database,
    Download,
    DownloadCloud,
    Edit3,
    Eye,
    FileArchive,
    FileCheck,
    FileCode,
    FilePlus2,
    FileText,
    FolderCheck,
    FolderX,
    HardDrive,
    Hash,
    Image,
    IndianRupee,
    Inbox,
    LayoutDashboard,
    LayoutGrid,
    Layers,
    LogOut,
    PieChart,
    PlayCircle,
    Plus,
    PlusCircle,
    Printer,
    QrCode,
    RefreshCw,
    RotateCcw,
    Save,
    Search,
    Settings2,
    ShieldCheck,
    Terminal,
    Trash2,
    Upload,
    UploadCloud,
    User,
    UserPlus,
    Users,
    Wallet,
    X,
    XCircle,
    Zap,
} from 'lucide';
import ApexCharts from 'apexcharts';

window.Alpine = Alpine;
window.ApexCharts = ApexCharts;

// Custom icons object for createIcons to resolve kebab-case
const activeIcons = {
    AlertCircle,
    AlertTriangle,
    AlignLeft,
    Archive,
    ArrowDownLeft,
    ArrowLeft,
    ArrowRight,
    BarChart3,
    Building,
    Building2,
    Briefcase,
    Check,
    CheckCircle2,
    ChevronDown,
    ChevronRight,
    ClipboardList,
    Clock,
    CreditCard,
    Database,
    Download,
    DownloadCloud,
    Edit3,
    Eye,
    FileArchive,
    FileCheck,
    FileCode,
    FilePlus2,
    FileText,
    FolderCheck,
    FolderX,
    HardDrive,
    Hash,
    Image,
    IndianRupee,
    Inbox,
    LayoutDashboard,
    LayoutGrid,
    Layers,
    LogOut,
    PieChart,
    PlayCircle,
    Plus,
    PlusCircle,
    Printer,
    QrCode,
    RefreshCw,
    RotateCcw,
    Save,
    Search,
    Settings2,
    ShieldCheck,
    Terminal,
    Trash2,
    Upload,
    UploadCloud,
    User,
    UserPlus,
    Users,
    Wallet,
    X,
    XCircle,
    Zap,
};

window.lucide = { createIcons, icons: activeIcons };

// Initialize Lucide Icons
document.addEventListener('DOMContentLoaded', () => {
    createIcons({ icons: activeIcons });
});

Alpine.start();
